[env:t-dongle-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

build_unflags = 
    -D ARDUINO_USB_MODE=1
    -DARDUINO_USB_MODE=1

build_flags = 
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D USE_HSPI_PORT=1
    ; TFT_eSPI display pin & driver settings for LilyGO T-Dongle-S3 (ST7735 80x160)
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D TFT_WIDTH=80
    -D TFT_HEIGHT=160
    -D ST7735_GREENTAB160x80=1
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_MOSI=3
    -D TFT_SCLK=5
    -D TFT_CS=4
    -D TFT_DC=2
    -D TFT_RST=1
    -D TFT_BL=38
    -D TFT_BACKLIGHT_ON=LOW
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SPI_FREQUENCY=27000000

lib_deps = 
    bodmer/TFT_eSPI @ 2.5.43
    links2004/WebSockets @ 2.4.1
    bblanchon/ArduinoJson @ 7.0.4

